---
name: readme

"on":
  push:
    branches:
      - master
    paths:
      - README.md
  workflow_dispatch:

jobs:
  readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Push readme
        uses: actionhippie/pushrm@v1
        if: github.event_name != 'pull_request'
        with:
          provider: dockerhub
          target: webhippie/mariadb
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          description: Docker image for mariadb
          readme: README.md

      - name: Push readme
        uses: actionhippie/pushrm@v1
        with:
          provider: quay
          target: quay.io/webhippie/mariadb
          apikey: ${{ secrets.QUAY_APIKEY }}
          readme: README.md

...
